todolistservice:
  build: ./
  ports:
    - "8080:8080"
  volumes:
    - ./build/libs:/app
  links:
    - postgres
    - kafka
    - zookeeper
    - elasticsearch
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
    SPRING_DATASOURCE_USERNAME: eventuate
    SPRING_DATASOURCE_PASSWORD: eventuate
    SPRING_DATASOURCE_TEST_ON_BORROW: "true"
    SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING: 1000
    EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING: 100
    EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS: 500
    ELASTICSEARCH_HOST: elasticsearch
    ELASTICSEARCH_PORT: 9300
    SPRING_PROFILES_ACTIVE: EventuatePolling

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
  environment:
      - http.host=0.0.0.0
      - network.publish_host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
  ports:
      - "9200:9200"
      - "9300:9300"

zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.17.0.RELEASE
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


kafka:
  image: eventuateio/eventuateio-local-kafka:0.17.0.RELEASE
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

postgres:
  image: eventuateio/eventuate-tram-postgres:0.6.0.RELEASE
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: eventuate
    POSTGRES_PASSWORD: eventuate

adminer:
    image: adminer:4.3.1-standalone
    ports:
        - 9080:8080

tramcdcservice:
  image: eventuateio/eventuate-tram-cdc-mysql-service:0.6.0.RELEASE
  ports:
    - "8099:8080"
  links:
    - postgres
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
    SPRING_DATASOURCE_USERNAME: eventuate
    SPRING_DATASOURCE_PASSWORD: eventuate
    SPRING_DATASOURCE_TEST_ON_BORROW: "true"
    SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING: 1000
    EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING: 100
    EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
    EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME: message
    SPRING_PROFILES_ACTIVE: EventuatePolling
